name: Sanity Checks

on:
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Lint
  lockfile_changes:
    name: Lockfile Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM Lockfile Changes
        uses: codepunkt/npm-lockfile-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # collapsibleThreshold: 25
          # failOnDowngrade: false
          # path: package-lock.json
          # updateComment: true

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  # Job 2: Build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
        env:
          CI: ''
