name: Sanity Checks

on:
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Lint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  # Job 2: Build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
        env:
          CI: ''
